
name: Build Kernel Test
on:
  push:
    branches:
      - android13-clo
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get -y install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd openjdk-11-jdk openjdk-11-jre
    - name: Building Kernel Poco F4
      run: ./build.sh
